Mobile and Desktop versions 1
SchoolOfCode/frontend-eng-example pull request #1
Opened 2024-08-09 12:42 UTC by Franz940

2024-08-09 14:01 UTC, tompsoc requested changes
This is brilliant dude :) nice use of semantic HTML and clean CSS. You've used some elements I don't think I ever did! I put some comments, have a read and ask any questions on the comment if something doesn't make sense.

2024-08-09 14:01 UTC, tompsoc commented on index.html
> +  <body>
I would probably wrap the top level of the application in a div with a class of wrapper. That way you don't need to turn the body into a grid/flex container :)

2024-08-09 14:01 UTC, tompsoc commented on index.html
> +    <section id="hero" class="hero-section">
Do you need the id?

2024-08-09 14:01 UTC, tompsoc commented on index.html
> +        src="/images/hero-mobile.png"
You could use srcset to pull in different images on mobile/desktop? :)

2024-08-09 14:01 UTC, tompsoc commented on index.html
> +
You could wrap your sections with main maybe?

2024-08-09 14:01 UTC, tompsoc commented on index.html
> +            <a href="https://www.facebook.com" class="link"> Facebook </a>
This links in the footer might make more sense semantically as a list? :)

2024-08-09 14:01 UTC, tompsoc commented on styles.css
> +body {
I think it might be useful to set box-sizing: border-box, that's a common default :)

2024-08-09 14:01 UTC, tompsoc commented on styles.css
> +  font-size: 16px;
I usually set font-size of 10px on the html/body, then I use rems in the rest of my code. Generally rems are recommended but I'm easy if you'd like to keep px!

2024-08-09 14:01 UTC, tompsoc commented on styles.css
> +  background-color: #f1911b;
If there are 1 or 2 key colours feel free to use css variables. Or leave in place - I'm easy :)

2024-08-09 14:01 UTC, tompsoc commented on styles.css
> +  color: black;
I'd probably try to keep to using hex consistently :)

2024-08-09 14:01 UTC, tompsoc commented on styles.css
> +.link {
I'd probably style the footer links as "a" elements under the footer nav or I'd consider slightly more specific naming :)

2024-08-09 14:01 UTC, tompsoc commented on styles.css
> +  display: flex;
If you made the links a list of links you wouldn't need to use flex for the footer links. You could just use a list and display block/inline when you want to go from stacked list to inline links. I'm easy on this one :)

2024-08-12 08:03 UTC, Franz940 commented on index.html
> +    <section id="hero" class="hero-section">
Not really actually, I think I added to make it semantic but I haven't to others elements so I will remove it.

2024-08-12 16:15 UTC, merged